#
# Defines environment variables.
#
# Authors:
#   Simon Steiger <simon.steiger@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Adaptions to Path
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:'/Users/simonsteiger/julia'
export PATH=$PATH:'/usr/local/opt/llvm/bin'

#Malmo
export MALMO_XSD_PATH=~/Playground/Malmo-0.30.0-Mac-64bit_withBoost/Schemas

# Conda related:
. /Users/simonsteiger/anaconda2/etc/profile.d/conda.sh

# Add SSH-Keys on reboot
# if [ ! -S ~/.ssh/ssh_auth_sock ]; then
#   eval `ssh-agent`
#     ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
#     fi
#     export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
#     ssh-add -l -K id_rsa id_rsa_old > /dev/null || ssh-add

SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  # hg            # Mercurial section (hg_branch  + hg_status)
  # package       # Package version
  # node          # Node.js section
  # ruby          # Ruby section
  # elixir        # Elixir section
  # xcode         # Xcode section
  # swift         # Swift section
  # golang        # Go section
  # php           # PHP section
  # rust          # Rust section
  # haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  # dotnet        # .NET section
  # ember         # Ember.js section
  # kubecontext   # Kubectl context section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)