export PEARL_ROOT=/Users/simonsteiger/.local/share/pearl
source /Users/simonsteiger/.local/share/pearl/boot/sh/pearl.sh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# PROMPT_TITLE='echo -ne "]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}"'
# export PROMPT_COMMAND="${PROMPT_COMMAND} ${PROMPT_TITLE}; "

if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='code'
else
   export EDITOR='nano'
fi

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

## System wide aliases
alias git='nocorrect git'
alias RR='R --no-save --quiet --min-vsize=2048M --min-nsize=45M'
alias config='nocorrect git --git-dir=/Users/simonsteiger/.myconf/ --work-tree=/Users/simonsteiger'
alias conda='nocorrect conda'
alias less='vimpager'
alias ls='exa'
alias chrome='open -a "Google Chrome"'
alias gst='git status'
alias sshm="ssh -t mendel export 'TERM_PROGRAM="iTerm.app" && bash -l'"

source ~/.iterm2_shell_integration.`basename $SHELL`

#source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#fpath=(/usr/local/share/zsh-completions $fpath)
fpath=(~/.custom-zsh/conda-zsh-completion $fpath)
zstyle ':completion::complete:*' use-cache 1
compinit --yes conda 

eval $(thefuck --alias)

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/opt/gettext/bin:$PATH"
